version: '3.8'

services:
  terraform:
    image: gen3tf
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform_runner
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws
    environment:
      - TF_VAR_region=us-east-1 # Example variable, modify as needed
    entrypoint: [ "/bin/sh" ]
    command: "dockerrun.sh"
    stdin_open: true
    tty: true

