services:
  terraform:
    image: gen3-terraform
    pull_policy: never  # This prevents Docker from trying to pull the image

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: terraform_runner
    # platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws
    environment:
      - TF_VAR_region=us-east-1 # Example variable, modify as needed
    entrypoint: [ "/bin/sh" ]
    command: "init.sh"
    stdin_open: true
    tty: true

