name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    with:
      python-poetry: 'false'
    secrets: inherit

  terraform-test:
    name: terraform test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "latest"
      - uses: extractions/setup-just@v2
      - run: just test
